### PR TITLE
✨ Adding TypeScript typings

### PR DESCRIPTION
**Pull request by dudeofawesome**

### CODE REVIEW

**Comment by kevva** [comment]
https://github.com/sindresorhus/ama/issues/439#issuecomment-280861804

**Comment by dudeofawesome** [comment]
The officially preferred method of distributing typings is now to bundle them with the package: https://github.com/DefinitelyTyped/DefinitelyTyped/#create-a-new-package

If you would still rather that typings are not part of this project, I'll add them to DT as suggested.

**Comment by SamVerschueren** [comment]
As you can read in the AMA, there's a reason we don't add them to the repo directly. So yes, feel free to add them to DT.

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide

**Pull request closed without merging**
